name: Extract AgriCulture ZIP

on: push

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use the token

      - name: Verify AgriCulture-extracted/AgriCulture exists
        run: |
          ls -l AgriCulture-extracted/AgriCulture  # List contents to verify location
          if [ ! -d "AgriCulture-extracted/AgriCulture" ]; then
            echo "AgriCulture-extracted/AgriCulture not found!";
            exit 1;
          fi

      - name: Move files from AgriCulture-extracted/AgriCulture to root
        run: |
          mv AgriCulture-extracted/AgriCulture/* .  # Move files from AgriCulture-extracted/AgriCulture to the root
          rmdir AgriCulture-extracted/AgriCulture  # Remove the now-empty subfolder
          rmdir AgriCulture-extracted  # Remove the empty parent folder

      - name: Commit extracted files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Moved extracted files to root"
          git push origin main
